<?php 

$config['tolk_active'] = '';
$config['tolk_max_upload'] = '0';
$config['tolk_type'] = '';
$config['tolk_folder'] = '';
$config['tolk_file_prefix'] = '';
$config['tolk_send_alert'] = '';
$config['tolk_send_confirmation'] = '';
$config['tolk_email'] = '';
$config['tolk_group'] = '';
$config['tolk_ads_per_page'] = '20';
$config['tolk_spamwords'] = 'http://000site.ru|познакомлюсь с парнем|http://magusbooks.ru|Разместим Ваши объявления|blackmagic1.com|magic-services.narod.ru|порно секс|Живые ключи|www.jguru.com|Гарантированный результат!|adult dating|href=http|любовная магия|http://raskrutka.|a href= http|carsautomat.100webspace.net|рассылка рекламы|swisswatch4u.ru|http://hottuning.net|user/view.php?|http://blogs.|witch-diana.com|/viagra|Ритуалы Вуду|http://blog.|free pics|/sitemap.xml|webs.com/|webspace.net/|rambler.ru/community/|Михаил только по факту|community.livejournal.com|элитные проститутки|/map.html|/Community/members/|zumudogz.ru|abudabig.t35.com|t35.com/|проститутки москвы|Михаил только по факту|www.m2.by|8-029-320-25-25|Принимаем предложения непосредственно от собственников квартир|[url=|&lta; href|href=" http://|href="http://|fantom-spb.ru/|Buy online|eltransporte.com|.co.uk/forum/index.php?|levitra medicina|levitra effetto|Forum levitra|.com/Forum/index.php?|levitra http://www.|replicagoldvertu.com|com/VERTU|Индивидуальный русскоговорящий гид|услуги переводчика|russianathens.gr|bla lba|Зайдите на сайт|решение как найти квартиру в Ми|Kvatera.com|KVATERA.|Есть адекватное решение, как|KVATERA|Есть адекватное решение, как|Зайдите на сайт Вконтакте в группу|"Квартира в Минске" и узнайте|и узнайте подробнее об этом|Сегодня можно посмотреть-Агент по факту|или предоплате 100% заселение';
$config['tolk_send_email_to'] = 'dakh@mail.ru';

/* End of file config.php */
/* Auto generated by guestbook Administration on : 2011.02.18 19:47:32 */
/* Location: modules/Guestbook/config/config.php */
