<?php 

$config['realt_active'] = '';
$config['realt_max_upload'] = '2';
$config['realt_type'] = 'photoqueue';
$config['realt_folder'] = '/home/vabby/www/neagent.by/files/pictures/';
$config['realt_file_prefix'] = '';
$config['realt_send_alert'] = '';
$config['realt_send_confirmation'] = '';
$config['realt_email'] = '';
$config['realt_group'] = '';
$config['realt_ads_per_page'] = '17';
$config['realt_post_delay'] = '3';
$config['realt_spamwords'] = 'познакомлюсь с парнем|http://magusbooks.ru|Разместим Ваши объявления|blackmagic1.com|magic-services.narod.ru|порно секс|Живые ключи|www.jguru.com|Гарантированный результат!|adult dating|href=http|любовная магия|http://raskrutka.|a href= http|carsautomat.100webspace.net|рассылка рекламы|swisswatch4u.ru|http://hottuning.net|user/view.php?|http://blogs.|witch-diana.com|/viagra|Ритуалы Вуду|http://blog.|free pics|/sitemap.xml|webs.com/|webspace.net/|rambler.ru/community/|Михаил только по факту|community.livejournal.com|элитные проститутки|/map.html|/Community/members/|zumudogz.ru|abudabig.t35.com|t35.com/|проститутки москвы|Михаил только по факту|www.m2.by|8-029-320-25-25|Принимаем предложения непосредственно от собственников квартир|[url=|&lta; href|href=" http://|href="http://|fantom-spb.ru/|Buy online|eltransporte.com|.co.uk/forum/index.php?|levitra medicina|levitra effetto|Forum levitra|.com/Forum/index.php?|levitra http://www.|replicagoldvertu.com|com/VERTU|Индивидуальный русскоговорящий гид|услуги переводчика|russianathens.gr|bla lba|Зайдите на сайт|решение как найти квартиру в Ми|Kvatera.com|KVATERA.|Есть адекватное решение, как|KVATERA|Есть адекватное решение, как|Зайдите на сайт Вконтакте в группу|"Квартира в Минске" и узнайте|и узнайте подробнее об этом|Сегодня можно посмотреть-Агент по факту|или предоплате 100% заселение';
$config['realt_black_action'] = 'deny';
$config['realt_show_phones'] = '1';
$config['realt_newpage'] = '0';
$config['realt_currency_name'] = array('Бел. руб','$', '€');
$config['realt_currency_rate'] = array('1','4981','7162');
$config['realt_temp_upload_folder'] = '/home/vabby/www/neagent.by/modules/Board/files/tmp/';
$config['board_upload_folder'] = '/home/vabby/www/neagent.by/files/pictures/';
 
/* End of file config.php */
/* Auto generated by realt Administration on : 2011.02.18 19:36:38 */
/* Location: modules/Realt/config/config.php */
