<?php 

$config['realt_active'] = '';
$config['realt_max_upload'] = '2';
$config['realt_type'] = 'photoqueue';
$config['realt_folder'] = '/home/vabby/www/neagent.by/files/pictures/';
$config['realt_file_prefix'] = '';
$config['realt_send_alert'] = '';
$config['realt_send_confirmation'] = '';
$config['realt_email'] = 'info@neagent.by'; //официальный email сайта, в которого письма клиентам идут
$config['realt_moderator_email'] = 'dakh2008@mail.ru'; // email moderatora, на который идут уведомления
$config['realt_group'] = '';
$config['realt_ads_per_page'] = '13';
$config['realt_ads_per_page_sutki'] = '992';
$config['realt_post_delay'] = '3';
$config['realt_spamwords'] = 'познакомлюсь с парнем|bling|\n|navaselle|там тоже можно снять|блинг|navaselle.net|bling.by|US Medica|2бефит|едицинская справка в бассейн|олдавский коньяк|наш интернет-магазин|теплостойкий клей|гни большого города|осуществляет оптовую продажу|gomeed|для массовой рассылки|шредеры производства|предлагаем к поставке|Рассылка без спама|винипласт ВНЭ|родаем дробилки|интернет казино|живицу сосновую|со склада в|редлагаю Неонол|миллионы потенциальных клиентов|перевозки по России|сотовый поликарбонат|се виды отгрузки|в Москве и регионах|предлагает широкий спектр|объявления без регистрации|rf-bazar|лакокрасочных материалов|плитных материалов|izomernn|ООО «Изомер»|44695922|узнают тысячи клиентов|ценник долго себя не заставил ждать|рассылка ваших обьявле|рассылка обьявлений|редлагаем Фторопласт|Оптовые поставки|предлагаем красители|Поставка со склада|установке натяжных потолков|органическое стекло марок|Размещу Ваше объявление|Трихлорэтилен|предлагает оборудование|предоставляет услуги|гофрокартон|ткань асбестовая|Винипласт листовой|Стали Урала|Синтанол|Регистрация в Минске и Минском районе|промышленного масла|светодиодных табло|http://magusbooks.ru|tinyurl|Разместим Ваши объявления|blackmagic1.com|magic-services.narod.ru|порно секс|Живые ключи|www.jguru.com|Гарантированный результат!|adult dating|href=http|любовная магия|http://raskrutka.|a href= http|carsautomat.100webspace.net|рассылка рекламы|swisswatch4u.ru|http://hottuning.net|user/view.php?|http://blogs.|witch-diana.com|/viagra|Ритуалы Вуду|http://blog.|free pics|/sitemap.xml|webs.com/|webspace.net/|rambler.ru/community/|Михаил только по факту|community.livejournal.com|элитные проститутки|/map.html|/Community/members/|zumudogz.ru|abudabig.t35.com|t35.com/|проститутки москвы|Михаил только по факту|www.m2.by|8-029-320-25-25|Принимаем предложения непосредственно от собственников квартир|[url=|&lta; href|href=" http://|href="http://|fantom-spb.ru/|Buy online|eltransporte.com|.co.uk/forum/index.php?|levitra medicina|levitra effetto|Forum levitra|.com/Forum/index.php?|levitra http://www.|replicagoldvertu.com|com/VERTU|Индивидуальный русскоговорящий гид|услуги переводчика|russianathens.gr|bla lba|Зайдите на сайт|решение как найти квартиру в Ми|Kvatera.com|KVATERA.|Есть адекватное решение, как|KVATERA|Есть адекватное решение, как|Зайдите на сайт Вконтакте в группу|"Квартира в Минске" и узнайте|и узнайте подробнее об этом|Сегодня можно посмотреть-Агент по факту|или предоплате 100% заселение';
$config['realt_number_error_mark'] = 'неправильно указан|неверный номер|номер недоступен|дозвониться|ничего не сдает|Номер не отвечает|не тот номер|Подстава|ложное|шутка|недоступно|Не звоните'; // Если в комментарии ил в жалобе это, то отправлять на модерацию. Работа с неправильными номерами
$config['realt_black_action'] = 'deny';
$config['realt_show_phones'] = '0'; // 1 - показывть телефоны , 0- показывать крестики и открывать в новом окне  2 -  ограничения 
$config['realt_show_phones_limit'] = '20'; // ограничение на показ телефонов  одному пользователю 
$config['realt_newpage'] = '0';   // Если крестики, то открывать в новом окне, чтоб было больше кликов
$config['realt_currency_name'] = array('Бел. руб','$', '€');
$config['realt_currency_rate'] = array('1','10000','13000');
$config['realt_temp_upload_folder'] = '/home/vabby/www/neagent.by/modules/Realt/files/tmp/';
$config['board_upload_folder'] = '/home/vabby/www/neagent.by/files/pictures/';
$config['realt_labels_flag'] = '0'; // показывать ли лэйбы 
$config['realt_email_confirm'] = '1';
$config['autocreate_prolongation_days'] = '5';
$config['realt_modify_date'] = '1';
$config['realt_moderate_min_name_lenth'] = '';
$config['realt_moderate_max_digits'] = '45';
$config['realt_moderate_max_digits_group'] = '10';
$config['realt_max_ads'] = '10'; // максимальное кол-во объявлений от одного пользователя и на один телефон 
$config['realt_autoupdate'] = '0'; // 1 или 0 или '' автоподнятие 
$config['realt_phone_verification'] = '1'; //  '1' или '0' при подаче объявления отправляется смс с кодом на номер подателя.  
$config['realt_phone_verification_cats'] = '1,3,13'; //  ''  или '1,3,4'   пусто - тогда все или список категорий


/* End of file config.php */
/* Auto generated by realt Administration on : 2011.02.18 19:36:38 */
/* Location: modules/Realt/config/config.php */
