<?php 

$config['sutki_vip_ads'] = array('http://neagent.by/nasutki/2-komn-nezavisimosti%%%2-комн. VIP квартира на сутки%%%http://neagent.by/themes/neagent_style/assets/images/sutki_vip.jpg');


/* End of file config.php */
/* Auto generated by realt Administration on : 2011.07.30 09:57:41 */
/* Location: modules/Realt/config/mycash.php */
