<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');


class Realt extends Module_Admin 
{
	/**
	 * Constructor
	 *
	 */
	function construct(){}


	// ------------------------------------------------------------------------


	/**
	 * Admin panel 
	 *
	 */
	function index()
	{

		/*
		 * Get the media folders
		 */
		$path = config_item('base_path').'/'.Settings::get('files_path');

		$iter = new RecursiveIteratorIterator(
			new RecursiveDirectoryIterator($path, RecursiveDirectoryIterator::KEY_AS_FILENAME), RecursiveIteratorIterator::SELF_FIRST);
		
		// Build the folder select drop down
		$folder_select = array();
		foreach ($iter as $file=>$entry)
		{
		    if ($entry->isDir() and substr($entry->getFileName(), 0, 5) != 'thumb')
		    {
		        $pre = ($iter->getDepth() > 0) ? str_repeat("&nbsp;", 2*$iter->getDepth()). ' &raquo; ' : '';
		    	$folder_select[$path.'/'.$entry->getFileName().'/'] = $pre.$entry->getFileName();
		    }
		}

		// Get groups list filtered on level <= current_user level
		$this->template['groups'] = array_filter(Connect()->model->get_groups(), array($this, '_filter_groups'));


		// Folders to template
		$this->template['realt_folder'] = form_dropdown('realt_folder', $folder_select, config_item('realt_folder'), 'class="w160"');

		// Admin view
		$this->output('admin/realt');
	}
	
	
	// ------------------------------------------------------------------------


	/**
	 * Saves Fancyupoad settings in /modules/Fancyupoad/config/config.php file
	 *
	 */	
	function save()
	{
		$this->load->helper('file');

		// Settings to save
		$keys = array
		(
			'realt_active',
			'realt_max_upload',
			'realt_type',
			'realt_folder',
			'realt_file_prefix',
			'realt_send_alert',
			'realt_send_confirmation',
			'realt_email',
			'realt_group',
			'realt_ads_per_page',
			'realt_post_delay',
			'realt_spamwords',
			'realt_black_action'
		);

		$settings = array_fill_keys($keys, '');

		// Feed array with Post data
		foreach ($_POST as $key => $val)
		{
			if (isset($settings[$key]))
				$settings[$key] = $val;
		}

		if ($settings['realt_ads_per_page'] == '')
		{
			$settings['realt_ads_per_page'] = 17;
		}
		
		if ($settings['realt_max_upload'] == '')
		{
			$settings['realt_max_upload'] = 0;
		}

		if ($settings['realt_post_delay'] == '')
		{
			$settings['realt_post_delay'] = 10;
		}
		
		/*
		 * Saving the file
		 */
		$conf  = "<?php \n\n";	 
		foreach ($settings as $key=>$val)
		{
			$conf .= "\$config['".$key."'] = '".$val."';\n";
		}

		// files end
		$conf .= "\n\n";
		$conf .= '/* End of file config.php */'."\n";
		$conf .= '/* Auto generated by realt Administration on : '.date('Y.m.d H:i:s').' */'."\n";
		$conf .= '/* Location: ' .$this->config->item('module_path').'Realt/config/config.php */'."\n";

		// Writing problem
		if ( ! write_file($this->config->item('module_path').'Realt/config/config.php', $conf))
		{
			$this->error(lang('ionize_message_error_writing_file'));				
		}
		else
		{
			$this->success(lang('module_realt_message_options_save'));				
		}
	}

	/**
	 * Groups filter callback function
	 *
	 */
	function _filter_groups($row)
	{
		// Current connected user level
		$user = Connect()->get_current_user();
		$this->current_user_level = $user['group']['level'];

		return ($row['level'] <= $this->current_user_level) ? true : false; 
	}


}
/* End of file realt.php */
/* Location: ./modules/Realt/controllers/admin/realt.php */