<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'article' => 
  array (
    'default/article' => 'Article',
    'articles/article_blog' => 'Blog Article',
    'articles/article_blog_list' => 'Blog List Article',
    'articles/article_search_url_mode' => 'Search form (URL)',
    'articles/article_search_integrated_mode' => 'Search form (integrated)',
  ),
  'page' => 
  array (
    'pages/page_blog' => 'Blog page',
    'pages/page_home_widgets' => 'Home Widget',
    'pages/page_home' => 'Home page',
    'default/page' => 'Page',
    'pages/page_register' => 'Register',
    'default/neagent' => 'neagent',
  ),
);


/* End of file views.php */
/* Auto generated by Themes Administration on : 2010.10.17 23:47:28 */
/* Location: application/../themes/hand_made/config/views.php */
